### ISSUE TITLE
Add columns in get_query

### ISSUE THREAD

**Issue by GinaStavropoulou** [balazsdukai/pgutils#2]
When I use [get_query](https://github.com/balazsdukai/pgutils/blob/23707328fc89625bbe9990ba5a9cb38eeb41118a/src/pgutils/connection.py#L283
) I would also like to have access to the column names of the table in order to create a DataFrame with the proper column names. Normally those can be found in the cursor.description. 

Just converting to dataframe does not preserve column names:
```
res = conn.get_query(query, query_params=query_params)
data = pd.DataFrame(res)
```

Is there maybe another way to get dataframe from the output if get_query?

**Comment by balazsdukai** [comment]
You can use the existing `get_dict` method to create a dataframe. Does that work for you?

```
res = conn.get_dict(query, query_params=query_params)
data = pd.DataFrame.from_records(res)
```

**Comment by GinaStavropoulou** [comment]
Yes it did! I had to inject parameter because `get_dict` does not have query_params, like this:

```
query = inject_parameters(query, query_params)
res = context.resources.db_connection.get_dict(query)
data = pd.DataFrame.from_records(res)
```
